- app-deployment.md
Writing down experience from the first application set up to run from now.js. Great for simple frontend only sites or `node.js` projects.
> Describes app deployment to now

- architecture-draft-v0.1.md
Architecture proposal for the mixed system of on-chain / off-chain.
> Architecture proposal

- developer-resources.md
- development.md
I tried to write up an introduction for the outside developers with links to whatever I could think of.
> Adds developer-resources document

- search-for-distributed-database.md
Here are my results of the distributed database research written down. I might have missed something or I might have had a broken test setup, so if you come to different results, please comment and we might come to something else in the end.
> Distributed database research and summary

- WT Hotel Architecture.md
- Change dp-pointers for url-pointers since we wont enforce the use of any protocol.
- Added content url pointer in the doc.
- Added small paragraph about governance of the data-standard on chain.
> Add url-pointers, content and standard governance in roadmap

- README.md
re-wrote the readme to be more clear and free of spelling mistakes
> Dave branch

- data-specification.md
This is a writeup of our work on research and design of data shape and specification. Along with the description on [SwaggerHub](https://app.swaggerhub.com/apis/windingtree/WTHotelDefinitions/0.0.2-pricing-avilability), this should go for a review and validation by any interested party.
Once this is approved and merged, I'll port it to Medium and we can publish a blogpost.
> feature: Adds an article on data specification

- developer-resources.md
Links a doc created as part of #23
> feature: Adds link to data description

- hotel-data-swagger.yaml
> fix: Make `quantity` required within AvailabilityForDay`.

- developer-guides/README.md
- developer-guides/reading-hotels.md
- developer-guides/registering-hotel.md
- developer-guides/removing-hotel.md
- developer-guides/updating-hotel.md
- developer-resources.md
This PR should result into multiple guides describing the current state of the hotel platform and how to access it, either directly with windingtree/wt-js-libs or with our soon-to-be REST APIs.
Don't forget to:
- State a version of a library or API against which the code should be run.
- Thoroughly comment the code.
- Describe the tooling required (such as how to get your wallet in a JSON format, how to get your Etherscan API KEY).
- Describe the limitations of the current state.
- Point out alternative approaches (such as direct blockchain access).
- Describe relations of possibly multiple WTIndex (local network, many indexes on Ropsten testnet).
> Developer guides - First version

- developer-guides/reading-hotels.md
- developer-guides/registering-hotel.md
- developer-guides/removing-hotel.md
- developer-guides/updating-hotel.md
It would be best if this was merged after https://github.com/windingtree/wt-read-api/pull/127 to prevent confusion, but it's no big deal.
> Developer guides - Read API

- blogposts/data-specification.md
- blogposts/search-for-distributed-database.md
- dev-updates/2018-Q1.md
- dev-updates/2018-Q2.md
- developer-resources.md
- development-handbooks/development.md
This is waiting for https://github.com/windingtree/wt-read-api/pull/126 and https://github.com/windingtree/wt-contracts/pull/198 to be merged
> Drop proposal next

- developer-guides/reading-hotels.md
- developer-guides/registering-hotel.md
- developer-guides/removing-hotel.md
- developer-guides/updating-hotel.md
> wt-write-api guides

- developer-guides/registering-hotel.md
This should be merged after https://github.com/windingtree/wt-write-api/pull/17 is resolved and merged to wt-write-api's master.
> docs: Reflect the latest changes in wt-write-api.

- developer-guides/reading-hotels.md
- developer-guides/registering-hotel.md
- hotel-data-swagger.yaml
> feat: Adds new rate plan data structure

- development-handbooks/tooling.md
In light of greenkeeper introduction, I've added a list of external tooling we use during development. I'm not sure if I haven't forgotten something, feel free to add or ask for more information if you think something is missing or unclear.
**Missing**
> feat: Introduces developer tooling page

- hotel-data-swagger.yaml
This PR reflects the discussion in #55 in the swagger docs.
> feat: Availability revision in swagger data

- developer-guides/registering-hotel.md
- developer-guides/updating-hotel.md
**Wait for versioning of wt-write-api to 0.3.0 before merging this.**
> feat: Adds availability to developer guides

- deployments.md
**Merge on November 16th 2018** after successful deployment of all services.
> 2018/11/16 - Documents new WTIndex addresses for demo, playground

- developer-guides/registering-hotel.md
- hotel-data-swagger.yaml
> improvement(model): implement windingtree/wtips#9
